/**
 * NOTE: This class is auto generated by the swagger code generator program (1.0.13).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Apuesta;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;

@Api(value = "apuesta", description = "the apuesta API")
public interface ApuestaApi {

    @ApiOperation(value = "agrega una apuesta nueva", nickname = "agregarApuesta", notes = "agrega un nuevo apuesta", tags={ "administradores", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "cotejo creado"),
        @ApiResponse(code = 400, message = "objeto invalido"),
        @ApiResponse(code = 409, message = "ya existe un objeto con este id") })
    @RequestMapping(value = "/apuesta/{idApuesta}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> agregarApuesta(@ApiParam(value = "id de apuesta a buscar",required=true) @PathVariable("idApuesta") String idApuesta,@ApiParam(value = "apuesta a agregar"  )  @Valid @RequestBody Apuesta apuesta);


    @ApiOperation(value = "busca una apuesta", nickname = "buscarApuesta", notes = "Enviando un ID valido devuelve la informacion de la apuesta ", response = Object.class, tags={ "apostadores", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "devolver el resultado obtenido", response = Object.class),
        @ApiResponse(code = 400, message = "parametro incorrecto") })
    @RequestMapping(value = "/apuesta/{idApuesta}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Apuesta> buscarApuesta(@ApiParam(value = "id de la apuesta a buscar",required=true) @PathVariable("idApuesta") String idApuesta);

}
